# esphome-version: next
substitutions:
  display_name: Smoker
  device_name: camp_chef

text_sensor:
  - platform: version
    name: "${display_name} - ESPHome Version"

switch:
  - platform: restart
    name: "Smoker Restart"
